DigiHub/force-app/main/default/objects/Asset/fields/customerName__c.field-meta.xml
<CustomField>
    <fullName>customerName__c</fullName>
    <label>customerName</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/customerNo__c.field-meta.xml
<CustomField>
    <fullName>customerNo__c</fullName>
    <label>customerNo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/customerRegDate__c.field-meta.xml
<CustomField>
    <fullName>customerRegDate__c</fullName>
    <label>customerRegDate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/deliveryExWorkDate__c.field-meta.xml
<CustomField>
    <fullName>deliveryExWorkDate__c</fullName>
    <label>deliveryExWorkDate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/firstRegDate__c.field-meta.xml
<CustomField>
    <fullName>firstRegDate__c</fullName>
    <label>firstRegDate</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/manufacturer__c.field-meta.xml
<CustomField>
    <fullName>manufacturer__c</fullName>
    <label>manufacturer</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/measuringPoint__c.field-meta.xml
<CustomField>
    <fullName>measuringPoint__c</fullName>
    <label>measuringPoint</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/modelRange__c.field-meta.xml
<CustomField>
    <fullName>modelRange__c</fullName>
    <label>modelRange</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/overhang__c.field-meta.xml
<CustomField>
    <fullName>overhang__c</fullName>
    <label>overhang</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/prodCode__c.field-meta.xml
<CustomField>
    <fullName>prodCode__c</fullName>
    <label>prodCode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/regNumCountryKey__c.field-meta.xml
<CustomField>
    <fullName>regNumCountryKey__c</fullName>
    <label>regNumCountryKey</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/suspension__c.field-meta.xml
<CustomField>
    <fullName>suspension__c</fullName>
    <label>suspension</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/truckAxle__c.field-meta.xml
<CustomField>
    <fullName>truckAxle__c</fullName>
    <label>truckAxle</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/typeVariant__c.field-meta.xml
<CustomField>
    <fullName>typeVariant__c</fullName>
    <label>typeVariant</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/vehicleNum__c.field-meta.xml
<CustomField>
    <fullName>vehicleNum__c</fullName>
    <label>vehicleNum</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/vehicleRegNum__c.field-meta.xml
<CustomField>
    <fullName>vehicleRegNum__c</fullName>
    <label>vehicleRegNum</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/vehicleTextData__c.field-meta.xml
<CustomField>
    <fullName>vehicleTextData__c</fullName>
    <label>vehicleTextData</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/vehicleType__c.field-meta.xml
<CustomField>
    <fullName>vehicleType__c</fullName>
    <label>vehicleType</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/Asset/fields/wheelBase__c.field-meta.xml
<CustomField>
    <fullName>wheelBase__c</fullName>
    <label>wheelBase</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/classes/retrieveAssetController.cls
public class retrieveAssetController {
    
    /*********************************************************************************************
    *@Description : AuraEnabled method that receiving asset to update , vin and Oem Vin retrieves from API and updates         
    *@Params      : String assetId, String vin, String oemVin                                                                   
    *@Return      : String response                                                                              
    *************************************************************************************************/
    @AuraEnabled
    public static String getAssetFromApi (String assetId, String vin, String oemVin ) {
        String sReturn;
        try {
            digitalHubGetData dhGetData = new digitalHubGetData();  
            String AssetJson = dhGetData.getData(vin,oemVin); 
            system.debug(AssetJson);
            if (AssetJson.contains('Error')) {
                sReturn = AssetJson;
            } else {
                sReturn = updateAsset(assetId,AssetJson);
                system.debug(sReturn);
            }
        } catch (Exception ex) {
            sReturn = ex.getMessage();
            system.debug(ex.getMessage());
        }
        return sReturn;
    }
    
    /*********************************************************************************************
    *@Description : Method that updates the Asset given the response from API         
    *@Params      : String assetId, String jsonStrn                                                                   
    *@Return      : String response                                                                              
    *************************************************************************************************/
    public static String updateAsset (String assetId, String jsonStr) {
        String sReturn = 'success';
        APIDigitalHubWrapper.AssetTruckWrapper resp = ( APIDigitalHubWrapper.AssetTruckWrapper ) JSON.deserialize(jsonStr, APIDigitalHubWrapper.AssetTruckWrapper.class);
        Asset assetToUpdate = new Asset(
            id = assetId,
            vehicleNum__c = resp.vehicleNum,
            vehicleRegNum__c = resp.vehicleRegNum,
            regNumCountryKey__c = resp.regNumCountryKey,
            manufacturer__c = resp.manufacturer,
            prodCode__c = resp.prodCode,
            modelRange__c = resp.modelRange,
            vehicleType__c = resp.vehicleType,
            typeVariant__c = resp.typeVariant,
            deliveryExWorkDate__c = resp.deliveryExWorkDate,
            firstRegDate__c = resp.firstRegDate,
            wheelBase__c = resp.wheelBase,
            overhang__c = resp.overhang,
            suspension__c = resp.suspension,
            truckAxle__c = resp.truckAxle,
            customerRegDate__c = resp.customerRegDate,
            customerNo__c = resp.customerNo,
            customerName__c = resp.customerName,
            measuringPoint__c = JSON.serialize(resp.measuringPoint),
            vehicleTextData__c = JSON.serialize(resp.vehicleTextData)
        );
        try {
            Database.update(assetToUpdate);
        } catch (Exception ex) {
            sReturn = ex.getMessage();
        }
        return sReturn;
    }
    
}