DigiHub/force-app/main/default/objects/MANDigiHubCredentials__c/MANDigiHubCredentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>MANDigiHubCredentials</label>
</CustomObject>

DigiHub/force-app/main/default/objects/MANDigiHubCredentials__c/fields/API_res__c.field-meta.xml
<CustomField>
    <fullName>API_res__c</fullName>
    <label>API_res</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/MANDigiHubCredentials__c/fields/client_id__c.field-meta.xml
<CustomField>
    <fullName>client_id__c</fullName>
    <label>client_id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/MANDigiHubCredentials__c/fields/client_secret__c.field-meta.xml
<CustomField>
    <fullName>client_secret__c</fullName>
    <label>client_secret</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/objects/MANDigiHubCredentials__c/fields/correlation_id__c.field-meta.xml
<CustomField>
    <fullName>correlation_id__c</fullName>
    <label>correlation_id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

DigiHub/force-app/main/default/classes/digitalHubGetData.cls
public class digitalHubGetData {
    
    public string getData( String vin, String oemVin ){
        
        String sReturn;
        HttpRequest req = new HttpRequest();
        HttpResponse res = new HttpResponse();
        Http http= new Http();
        String sEndPoint;
        MANDigiHubCredentials__c manDig = MANDigiHubCredentials__c.getOrgDefaults();
        sEndPoint =  manDig.API_res__c + oemVin + '/' + vin;          
        req.setHeader('Client-id', manDig.client_id__c);
        req.setHeader('Client-secret', manDig.client_secret__c);
        req.setHeader('correlation-id', manDig.correlation_id__c);
        req.setEndpoint(sEndPoint);
        req.setMethod('GET');
        req.setCompressed(true);
        req.setTimeout(1200);        
        
        try {
            res = http.send(req);
            
            if(res.getBody() != null )
            {
                sReturn = res.getBody();  
            }
            else{
                sReturn = '{"errorDescription":"Error in service response"}';  
            }
        } catch(System.CalloutException e) {
            sReturn = e.getMessage();
        }
        return sReturn;        
    }  
}